apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-acre-fund-deployment
  labels:
    app: one-acre-fund-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: one-acre-fund-node-app
  template:
    metadata:
      labels:
        app: one-acre-fund-node-app
    spec:
      containers:
      - name: one-acre-fund-node-app
        image: bruno74t/one-acre-fund-node-app:v.1.0.2
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: one-acre-fund-service
spec:
  selector:
    app: one-acre-fund-node-app
  ports:
    - protocol: TCP
      port: 30200
      targetPort: 3000
      nodePort: 30200
  type: NodePort
