# k8s/app.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: bruno74t/codescreen_app:v1.0.1
          env:
            - name: POSTGRES_URI
              value: postgres://postgres:password@db:5432/api_db
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort # Or LoadBalancer if needed
